image: alpine

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}

cache:
  key: primary
  paths:
    - .stack
    - .stack-work

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: haskell
  # See https://gitlab.com/gitlab-org/gitlab-runner/issues/2838
  cache:
    key: primary
    policy: pull # Only push from test (even though it runs later)
    paths:
      - .stack
      - .stack-work
  script:
    - mkdir bin
    - apt-get update
    - apt-get install -y liblzma-dev
    - stack install --local-bin-path ./bin
  artifacts:
    expire_in: 1 week
    paths:
      - bin/

test:
  stage: test
  image: haskell
  dependencies: []
  script:
    - apt-get update
    - apt-get install -y liblzma-dev
    - stack build hlint weeder
    - stack exec hlint -- .
    - stack exec weeder -- . --build
    - stack test --coverage
    - mkdir coverage
    - cp -a $(stack path --local-hpc-root)/. ./coverage/
  artifacts:
    expire_in: 1 week
    paths:
      - coverage/

image_build:
  stage: test # if on master, run alongside tests
  image: docker:latest
  services:
    - docker:dind
  cache: {}
  dependencies:
    - build
  script:
    - apk add --no-cache xz-libs musl
    - cp /usr/lib/liblzma.so.5 .
    - cp /usr/lib/liblzma.so.5.2.4 .
    - cp /lib/libc.musl-x86_64.so.1 .
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - master

deploy_image:
  stage: deploy
  environment:
    name: dev
  cache: {}
  dependencies: []
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - cd deploycfg
    - sed -i "s/__CI_ENVIRONMENT_SLUG__/${CI_ENVIRONMENT_SLUG}/" dev.yml service.yml
    - sed -i "s/__IMAGE__/$(echo ${IMAGE_NAME} | sed -e 's/\//\\\//g')/" dev.yml
    - kubectl apply -f dev.yml
    - kubectl apply -f service.yml
    - kubectl rollout status -f dev.yml
  only:
    - master

pages:
  stage: deploy
  cache: {}
  dependencies:
    - test
  script:
    - mkdir -p public/coverage
    - mv coverage/ public/
  artifacts:
    paths:
    - public
    expire_in: 30 days
  only:
    - master