image: haskell:latest

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work

stages:
  - build
  - test

build:
  stage: build
  script:
    - stack build

test:
  stage: test
  script:
    - stack test