- package:
  - name: impatience
  - section:
    - name: test:impatience-test
    - message:
      - name: Redundant build-depends entry
      - depends: tasty-discover
    - message:
      - name: Weeds exported
