version: '3'
services:
    impatience:
        build: .
        image: impatience
        command: impatience
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - impatience
