name: impatience
version: 0.1.0.0
github: csamak/impatience
license: Apache
author: Cameron Samak
maintainer: Cameron Samak
copyright: 2018 Cameron Samak
extra-source-files:
  - README.md

dependencies:
  - base

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
    - -fno-warn-missing-signatures
    - -O2
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
  dependencies:
    - aeson
    - blaze-html
    - containers
    - lens
    - servant-blaze
    - servant-server
    - servant-swagger
    - swagger2
    - wai
    - wai-logger
    - warp

executables:
  impatience-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -O2
    dependencies:
      - impatience

tests:
  impatience-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -fno-warn-missing-signatures
    - -fno-warn-orphans
    dependencies:
      - impatience
      - aeson
      - blaze-html
      - generic-random
      - hedgehog
      - QuickCheck
      - servant-server
      - servant-swagger
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-hspec
      - tasty-hunit
