name: impatience
version: 0.1.0.0
github: csamak/impatience
license: Apache
author: Cameron Samak
maintainer: Cameron Samak
copyright: 2018 Cameron Samak
extra-source-files:
  - README.md

dependencies:
  - base
ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Werror
  - -O2

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - lens
    - servant-server
    - servant-swagger
    - servant-swagger-ui
    - swagger2
    - wai
    - wai-logger
    - warp

executables:
  impatience-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - impatience

tests:
  impatience-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
      - impatience
      - generic-random
      - hedgehog
      - QuickCheck
      - servant-server
      - servant-swagger
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-hspec
      - tasty-hunit
      - transformers
