DROP DATABASE IF EXISTS impatience;
CREATE DATABASE impatience;
\c impatience
CREATE TABLE jobs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref_id TEXT NULL,
  "name" TEXT NOT NULL,
  start_time timestamptz NOT NULL DEFAULT NOW()
);
CREATE TABLE progresses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INT REFERENCES jobs(id),
  completed INT NOT NULL,
  total INT NOT NULL,
  reported_time timestamptz NOT NULL DEFAULT NOW()
);
