apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: impatience
  labels:
    app: __CI_ENVIRONMENT_SLUG__
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    type: "RollingUpdate"  
  selector:
    matchLabels:
      app: __CI_ENVIRONMENT_SLUG__
  template:
    metadata:
      labels:
        app: __CI_ENVIRONMENT_SLUG__
    spec:
      imagePullSecrets:
        - name: registry-impatience-gitlab-key
      containers:
        - name: impatience
          image: __IMAGE__
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /annieareyouok
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /annieareyouok
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          ports:
            - containerPort: 1234
              name: "external"
              protocol: "TCP"
          args:
          - impatience-exe
