apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: impatience
  labels:
    app: __CI_ENVIRONMENT_SLUG__
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: "RollingUpdate"  
  selector:
    matchLabels:
      app: __CI_ENVIRONMENT_SLUG__
      name: "impatience"
  template:
    metadata:
      labels:
        app: __CI_ENVIRONMENT_SLUG__
    spec:
      imagePullSecrets:
        - name: registry-impatience-gitlab-key
      containers:
        - name: impatience
          image: __IMAGE__
          imagePullPolicy: Always
          args:
          - impatience