apiVersion: apps/v1
kind: Deployment
metadata:
  name: impatience
  labels:
    app: impatience
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    type: "RollingUpdate"  
  selector:
    matchLabels:
      app: impatience
  template:
    metadata:
      labels:
        app: impatience
    spec:
      containers:
        - name: impatience
          image: impatience.azurecr.io/impatience
          imagePullPolicy: Always
          env:
          - name: IMPATIENCE_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: impatience-conn
                key: conn-string
          livenessProbe:
            httpGet:
              path: /annieareyouok
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /annieareyouok
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          ports:
            - containerPort: 1234
              name: "external"
              protocol: "TCP"
          args:
          - impatience-exe
